create schema UNICAR;



create table CLIENTE (
IDCLIENTE TINYINT NOT NULL AUTO_INCREMENT, 
NOME VARCHAR(30),
EMAIL VARCHAR(200),
SENHA VARCHAR(15),
PRIMARY KEY (IDCLIENTE)
)
;
create TABLE VAGA (
IDVAGA tinyint NOT NULL AUTO_INCREMENT,
LOCALV VARCHAR(100) NOT NULL,
DATAV DATETIME NOT NULL,
PRIMARY KEY (IDVAGA)
);
